import type { Metadata } from 'next'
import { Inter as FontSans } from "next/font/google"
import './globals.css'
import AuthChecker from '@/app/hooks/use-auth-check'
import { cn } from './utils/cn'
import App from 'next/app'

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthChecker>
        <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>{children}</body>
      </AuthChecker>
    </html>
  )
}
